CREATE TABLE ATADAS.CTRL_INSTANCE_ID 
(
INSTANCE_ID VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(500),
ALLOW_BATCH_CREATE VARCHAR(1),
FREQUENCY VARCHAR(20),
DAY_OF_MONTH  VARCHAR(20)
);

CREATE TABLE ATADAS.CTRL_BATCH_NAME
(
INSTANCE_ID VARCHAR(20) NOT NULL,
BATCH_ID INTEGER GENERATED ALWAYS AS IDENTITY,
BATCH_START_TS TIMESTAMP,
BATCH_END_TS TIMESTAMP,
BATCH_STATUS	VARCHAR(50)
);

CREATE TABLE ATADAS.CTRL_ETL_JOBS 
(
INSTANCE_ID VARCHAR(20) NOT NULL,
JOB_NAME VARCHAR(100),
JOB_DESCRIPTION	VARCHAR(200),
JOB_TYPE VARCHAR(20),
RUN_FREQUENCY INTEGER,
INCLUDE_IN_BATCH VARCHAR(1)
);

-- COMMENT ON ATADAS.CTRL_ETL_JOBS.RUN_FREQUENCY IS "'1 DAYS' for daily, '7 DAYS' for weekly and '1 MONTH' for monthly"

CREATE TABLE ATADAS.CTRL_BATCH_JOBS 
(
INSTANCE_ID VARCHAR(20) NOT NULL,
JOB_PROCESS_ID BIGINT,
JOB_NAME VARCHAR(100),
BATCH_ID INTEGER,
JOB_START_TS TIMESTAMP,
JOB_END_TS TIMESTAMP,
EXTRACT_DATE_FROM TIMESTAMP,
EXTRACT_DATE_TO TIMESTAMP,
JOB_STATUS	VARCHAR(50)
);

CREATE TABLE ATADAS.CTRL_JOB_DEPENDENCIES 
(
INSTANCE_ID VARCHAR(20) NOT NULL,
JOB_NAME VARCHAR(100),
DEPENDANT_JOB_NAME VARCHAR(100),
DESCRIPTION VARCHAR(200)
);



CREATE TABLE ATADAS.CTRL_PARAMETERS
(
INSTANCE_ID VARCHAR(20) NOT NULL,
JOB_NAME VARCHAR(100) NOT NULL,
PARAM_NAME VARCHAR(100),
PARAM_VALUE VARCHAR(100)
)