--#SET TERMINATOR @
CREATE OR REPLACE FUNCTION ATADAS.UDF_JOB_RUNNABLE
 (IN P_JOB_NM VARCHAR(100),
  IN P_BATCH_ID INTEGER
 )
 RETURNS INTEGER
	
LANGUAGE SQL
DETERMINISTIC
READS SQL DATA
NO EXTERNAL ACTION 
	
BEGIN 
  DECLARE SQL_STMT VARCHAR (2000);
  DECLARE stmt  VARCHAR (2000);
  DECLARE JOB_NM VARCHAR (100);
  DECLARE JOB_STS VARCHAR (20);
  DECLARE countrows INT DEFAULT 0;
  DECLARE EOF INT DEFAULT 1;
  DECLARE SQLCODE INTEGER DEFAULT -1;
  DECLARE FLAG INTEGER DEFAULT 0;
  DECLARE C_JOB_NM CURSOR FOR C_STMT;
  
  
--  SET stmt = 'SET ? = (SELECT JOB_NAME FROM '||'ATADAS'||'.CTRL_JOB_DEPENDENCIES WHERE DEPENDANT_JOB_NAME='''||P_JOB_NM||''')';
	SET stmt ='SELECT JOB_NAME FROM '||'ATADAS'||'.CTRL_JOB_DEPENDENCIES WHERE DEPENDANT_JOB_NAME='''||P_JOB_NM||'''';
	PREPARE C_STMT FROM stmt;
	
	SELECT COUNT(1) INTO countrows FROM ATADAS.CTRL_JOB_DEPENDENCIES WHERE  DEPENDANT_JOB_NAME=P_JOB_NM;
	
	OPEN C_JOB_NM;
	
WHILE (EOF <= countrows AND SQLCODE =0) DO 
SET EOF = EOF+1;

	FETCH FROM C_JOB_NM INTO JOB_NM;
  
--	SET stmt= 'SET ? = (SELECT JOB_STATUS FROM ATADAS.CTRL_BATCH_JOBS WHERE UPPER(JOB_NAME) = UPPER('||JOB_NM||')''';
--	PREPARE SQL_STMT FROM stmt;
--	EXECUTE SQL_STMT INTO JOB_NM,JOB_STS;

	SELECT JOB_STATUS INTO JOB_STS FROM ATADAS.CTRL_BATCH_JOBS WHERE UPPER(JOB_NAME) = UPPER(JOB_NM) AND BATCH_ID = P_BATCH_ID;	
	IF (UPPER(JOB_STS) <> 'COMPLETE') THEN
	SET FLAG = 1;
	END IF;
END WHILE;

RETURN FLAG;
END@